//
// Created by Luciano on 25/04/2017.
//

#ifndef HAZERON_GLOBAL_SCANNER_FETCH_PLAYER_DATA_H
#define HAZERON_GLOBAL_SCANNER_FETCH_PLAYER_DATA_H


#endif //HAZERON_GLOBAL_SCANNER_FETCH_PLAYER_DATA_H
